name: 'coverage'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          package-manager: yarn
          threshold: 90 